### ISSUE TITLE
Helm chart for installing?

### ISSUE THREAD

**Issue by samip5** [bugfest/tor-controller#1]
It would be nice if you could package it up in Helm, so that it's relatively easy to deploy and keep up-to-date. :)

**Comment by bugfest** [comment]
That's a good point @samip5. Going to work on it

**Comment by bugfest** [comment]
Hi @samip5, I still need to publish the helm chart somewhere public, in the mean time you can try with:

`
helm upgrade --install --create-namespace --namespace tor-controller tor-controller ./helm/tor-controller
`

**Comment by bugfest** [comment]
I'm hosting the chart in github pages for now. Here you have the updated procedure:

```
$ helm repo add bugfest https://bugfest.github.io/tor-controller
$ helm upgrade --install --create-namespace --namespace tor-controller tor-controller bugfest/tor-controller
```
