### ISSUE TITLE
EndGame Support

### ISSUE THREAD

**Issue by pro81723** [bugfest/tor-controller#15]
Hello is it possible to use  custom lua models for nginx? Such as https://github.com/onionltd/EndGame

**Comment by bugfest** [comment]
Hi @pro81723, thanks for using the project!

I've never used [onionltd/EndGame](https://github.com/onionltd/EndGame) before but I've poked around the code a bit. It looks like Tor and Nginx configurations are quite coupled. I wonder if it'd be possible to split the configuration and parts of the protections to the Tor daemon in tor-controller (that should be pretty easy), and isolate the chapta generation/control and rate-limiting functions for the services behind tor-controller's onionbalance. That way we can keep tor-controller as much agnostic as possible, just focused on transport and you get the protections you expect for the site.

Do you think that approach might work for you?

**Comment by hiringaccounthere** [comment]
Hi there!

I have been checking your profile and I would be interested in hiring you for some specific projects related to your project (paid of course, with cryptocurrencies)

Let me know if we can talk in Dino, mail or any other way you prefer

Here you have my PGP with a valid email associated: https://pastebin.com/r6pP4GW8

Waiting to get in touch!

**Comment by bugfest** [comment]
Thanks for the offer @hiringaccounthere

**Comment by bugfest** [comment]
@pro81723 I'll track your request as a use case or deployment example in the future. Closing this issue for the time being.
