### ISSUE TITLE
[REQUEST] Contact information

### ISSUE THREAD

**Issue by hiringaccounthere** [bugfest/tor-controller#16]
Hi again,

Could you post or share any contact information? I want to hire you for something specific related to your repository, it would be cool if we could discuss it and if you are not interested or too busy now I won't bother you more. Of course, I do not think nobody should work for free and I would like to pay you.

Waiting for your answer

**Comment by bugfest** [comment]
Hi @hiringaccounthere,

I'm happy to implement (for free) new tor-controller's features as long as their use cases are generic, beneficial for the users and can be openly shared with the rest of the community (FOSS). 

Anyhow, if you want to discuss your case outside github, you can reach me by email: https://pastebin.com/QkNxuV7w
