### ISSUE TITLE
[REQUEST] tor-controller as http proxy

### ISSUE THREAD

**Issue by kevin96666** [bugfest/tor-controller#19]
Dear, I would like to use tor-controller as a http proxy to make http request on the web.

Can't see (reading your documentation) how to create a kube service (internal/external) to be bind to the Tor POD (tor launched with the option HTTPTunnelPort:XXX)

Could you help me ?

**Comment by bugfest** [comment]
Hi @kevin96666, 

Thanks for your suggestion. I'm happy to inform you that functionality is part of the roadmap and I've been working on it for the last few weeks and It will be ready soon. I'll close this ticket as soon as it is available.

Cheers!

**Comment by bugfest** [comment]
Hi @kevin96666, I'm testing a new Tor object that will allow you to get Socks/HTTPTunnel/DNS and NATD services in your cluster with traffic being routed thru the Tor network. Branch: [tor-crd-0.6.1](/bugfest/tor-controller/tree/tor-crd-0.6.1)

In your ticket you specifically ask for HTTP Proxy but Tor daemon natively only supports Socks and HTTPTunnel (HTTP Connect; e.g in curl using `-p/--proxytunnel` option) ones. If you really need an HTTP Proxy service you might want to deploy a HTTP Proxy to Socks application to to the translation. Would that solve your problem?
