### ISSUE TITLE
[BUG] `0.6.1` image tag missing from image registry

### ISSUE THREAD

**Issue by conneryn** [bugfest/tor-controller#22]
**Describe the bug**
The `0.1.6` release successfully published the images to the image registry (quay.io) under the `latest` tag, but does not appear to have published the version pegged tags (`0.6.1`).

See: 
https://quay.io/repository/bugfest/tor-controller?tab=tags&tag=latest
https://quay.io/repository/bugfest/tor-onionbalance-manager?tab=tags&tag=latest

**To Reproduce**
Install the latest version via helm (0.1.6).  Observe images fail to be pulled.

Check https://quay.io/repository/bugfest/tor-controller?tab=tags&tag=latest, and see that `0.6.1` is missing.

**Expected behavior**
Both `latest` and `0.6.1` image tags should be available on the image repository.

**Additional information**

Error during pod startup:
```
Failed to pull image "quay.io/bugfest/tor-controller:0.6.1": rpc error: code = NotFound
```

**System (please complete the following information):**
 - Platform: amd64
 - Version v1.23.8+k3s2

**Additional context**
Installed via helm.

**Comment by bugfest** [comment]
Hi @conneryn, thanks for the heads up. I've re-pushed the tag and the build action has just started

**Comment by bugfest** [comment]
Hi @conneryn the images have been pushed
