### ISSUE TITLE
Vanguards Tor Addon 

### ISSUE THREAD

**Issue by pullrequestsbuydrugs** [bugfest/tor-controller#23]
Hello great work and thank you for actively maintaining this repo. Was there any reason why you did not include the Vanguards Tor Addon?

**Comment by bugfest** [comment]
Hi @pullrequestsbuydrugs, 

It's a good idea, I can add it to the project's TODO. Nevertheless AFAIK you can add Vanguards addon yourself by deploying a sidecar or standalone vanguard alongside the Tor instance, as long as you enable the Tor Control Port feature in your Tor manifest.

Regards,
BF
