### ISSUE TITLE
[REQUEST] x25519 auth client key generation 

### ISSUE THREAD

**Issue by Kuberwear** [bugfest/tor-controller#27]
Hello can you please make a x25519 generation feature? For example Tim has a ebook that only a select group of people can access. Rather than needing to contact Tim for auth credentials they can pay a fee and upon payment confirmation be give. There x25519 key.

Service must restart for clients upon revoking but not when being created so I'd imagine it's possible.

Thanks,
Kuberwear

**Comment by bugfest** [comment]
Hi @Kuberwear, 

Trying to understand your use case. I assume you're referring to authorized clients.

The operator might be patched to use new secrets from the manifest but here we rely on k8s's secret volume mounts. I wonder if what you're trying to achieve would be much easier to implement with a custom sidecar. Can you draft a more technical proposal so I can evaluate the implementation?

**Comment by bugfest** [comment]
Closing after no reply
