### ISSUE TITLE
No arm64 containers

### ISSUE THREAD

**Issue by samip5** [bugfest/tor-controller#3]
Please default to making multi-arch containers when ever you create a Docker project. More so when creating an Kubernetes one.

$ k logs -n tor example-onion-service-tor-daemon-f8f94c688-mgwp4
```
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by bugfest** [comment]
Hi @samip5, good point. I got the images build automated in quay and it defaults to amd64; going to migrate it to github actions so that we can get multiarch

**Comment by samip5** [comment]
Please look at this: https://github.com/samipsolutions/tor-controller/blob/master/.github/workflows/main.yml

**Comment by bugfest** [comment]
Thanks @samip5, that's all I need thanks. Going to try to integrate it with my registry at quay

**Comment by bugfest** [comment]
I show your typo, testing the fix now

**Comment by samip5** [comment]
It works, but you may want to tweak up the which tag it pushes to as it's set to latest currently. :)

![image](https://user-images.githubusercontent.com/1703002/151676204-48b13802-bd05-44b9-ae2b-fb7768454a0c.png)

**Comment by bugfest** [comment]
Thanks for trying it out!! 

Yeah, I noticed. I was waiting for that 3h build to finish before pushing the changes: https://github.com/bugfest/tor-controller/commit/ac14ba6416fefb514270e1a5ed35226e328b275e. Gonna try to build the one maching the chart app version so we don't need the override.

**Comment by bugfest** [comment]
I'm building a new app version `0.3.2` (Chart `0.1.1`) to check everything is fine. I've manually patched the tags on the current multi-arch images adding `0.3.1` so Chart `0.1.0` should work without the override.

**Comment by bugfest** [comment]
Closing this issue. @samip5 if you have any problem

**Comment by carronmedia** [comment]
Hi, sorry to resurrect a closed ticket, but I'm trying to install this on a Raspberry Pi 4 cluster running K3S and I'm still getting a CrashLoopBackOff status of the controller manager pod, which indicates that it's trying to pull down an image for the wrong architecture.

I've tried installing via Helm and directly with hack/install.yaml. Do I need to do something else to install this for arm64?

**Comment by samip5** [comment]
> Hi, sorry to resurrect a closed ticket, but I'm trying to install this on a Raspberry Pi 4 cluster running K3S and I'm still getting a CrashLoopBackOff status of the controller manager pod, which indicates that it's trying to pull down an image for the wrong architecture.
> 
> I've tried installing via Helm and directly with hack/install.yaml. Do I need to do something else to install this for arm64?

Forgot to check if it actually got deployed on arm64 as I have multi-arch on my cluster... So not sure.

**Comment by bugfest** [comment]
Hi @carronmedia, 

I've checked the 3 containers should havean  arm64 version available:

- ﻿https://quay.io/repository/bugfest/tor-controller/manifest/sha256:22d65b7e1838ab60427db6aa8604325b3a2f2a211da14aba2c0397ba850bdaa2
- https://quay.io/repository/bugfest/tor-daemon-manager/manifest/sha256:969cf3881cc60318af6bf6d6d36fd0e78fa8269396282382d53a43d4e690aa9c
- https://quay.io/repository/bugfest/tor-onionbalance-manager/manifest/sha256:62ed8549078d20d46f6a7c8ae909d40238dbd4e47752da73a1a33395efcec23f

The creash might be due to a wrong version in the image tag generated by our helm chart. I'm got to review it. In the mean time, can you provide some more details on your issue? Can you run a `kubectl describe pod` on the failing one and provide the output?

**Comment by carronmedia** [comment]
Thank you both for your quick responses!

Here is the output:

`Name:         tor-controller-controller-manager-76cfd688fb-fsnw2
Namespace:    tor-controller-system
Priority:     0
Node:         -------------------
Start Time:   Tue, 01 Mar 2022 09:36:57 +0000
Labels:       control-plane=controller-manager
              pod-template-hash=76cfd688fb
Annotations:  kubectl.kubernetes.io/default-container: manager
Status:       Running
IP:           -------------------
IPs:
  IP:           -------------------
Controlled By:  ReplicaSet/tor-controller-controller-manager-76cfd688fb
Containers:
  manager:
    Container ID:  containerd://4094ff8512b64e2ee27bdcaa18534c0694b6088190239e553062ab52b9f6569d
    Image:         quay.io/bugfest/tor-controller:latest
    Image ID:      quay.io/bugfest/tor-controller@sha256:22d65b7e1838ab60427db6aa8604325b3a2f2a211da14aba2c0397ba850bdaa2
    Port:          <none>
    Host Port:     <none>
    Command:
      /manager
    Args:
      --config=controller_manager_config.yaml
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 01 Mar 2022 09:42:09 +0000
      Finished:     Tue, 01 Mar 2022 09:42:09 +0000
    Ready:          False
    Restart Count:  3
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:        10m
      memory:     64Mi
    Liveness:     http-get http://:8081/healthz delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:    http-get http://:8081/readyz delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /controller_manager_config.yaml from manager-config (rw,path="controller_manager_config.yaml")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-cxmnn (ro)
  kube-rbac-proxy:
    Container ID:  containerd://d2a72b12d7d249c5b811fc0aef4f48651e840a3453cf9b0774ee554758741e7f
    Image:         gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
    Image ID:      gcr.io/kubebuilder/kube-rbac-proxy@sha256:db06cc4c084dd0253134f156dddaaf53ef1c3fb3cc809e5d81711baa4029ea4c
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --secure-listen-address=0.0.0.0:8443
      --upstream=http://127.0.0.1:8080/
      --logtostderr=true
      --v=10
    State:          Running
      Started:      Tue, 01 Mar 2022 09:41:15 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-cxmnn (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  manager-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      tor-controller-manager-config
    Optional:  false
  kube-api-access-cxmnn:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    5m39s                default-scheduler  Successfully assigned tor-controller-system/tor-controller-controller-manager-76cfd688fb-fsnw2 to -------------------
  Warning  FailedMount  5m39s                kubelet            MountVolume.SetUp failed for volume "manager-config" : failed to sync configmap cache: timed out waiting for the condition
  Normal   Pulled       89s                  kubelet            Successfully pulled image "quay.io/bugfest/tor-controller:latest" in 4m4.933183535s
  Normal   Pulled       85s                  kubelet            Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0" already present on machine
  Normal   Created      84s                  kubelet            Created container kube-rbac-proxy
  Normal   Started      82s                  kubelet            Started container kube-rbac-proxy
  Normal   Pulled       80s                  kubelet            Successfully pulled image "quay.io/bugfest/tor-controller:latest" in 2.127169962s
  Normal   Pulled       62s                  kubelet            Successfully pulled image "quay.io/bugfest/tor-controller:latest" in 1.151222775s
  Normal   Pulling      30s (x4 over 5m34s)  kubelet            Pulling image "quay.io/bugfest/tor-controller:latest"
  Normal   Pulled       29s                  kubelet            Successfully pulled image "quay.io/bugfest/tor-controller:latest" in 733.820068ms
  Normal   Created      29s (x4 over 87s)    kubelet            Created container manager
  Normal   Started      28s (x4 over 85s)    kubelet            Started container manager
  Warning  BackOff      26s (x6 over 75s)    kubelet            Back-off restarting failed container`

**Comment by bugfest** [comment]
HI @carronmedia, thanks for the output. The containers are being pulled correctly. It's in a crashloop because it cannot mount the tor-controller configmap. Can you try to uninstall, update the repo and just try the defaults?

```bash
$ helm uninstall ...
$ helm repo update
$ helm upgrade --install \
      --create-namespace --namespace tor-controller \
      tor-controller bugfest/tor-controller
```
