### ISSUE TITLE
[REQUEST] Namespaced Support

### ISSUE THREAD

**Issue by pingwin** [bugfest/tor-controller#33]
**Is your feature request related to a problem? Please describe.**
The ClusterRole appears to be over-provisioned. Provide an option for namespaced access to the kubernetes environment.

**Describe the solution you'd like**
Implement through configuration or discovery, the ability to limit requested resources (configmaps, secrets, etc) to the namespace it's installed in or a list of namespaces. 

**Describe alternatives you've considered**
There appears to be no documented support to minimize permissions. 

**Additional context**
`helm template bugfest/tor-controller` will show the ClusterRole that hopefully could be a Role instead.

**Comment by bugfest** [comment]
Hi @pingwin, thanks for your request! I do agree current access levels can be improved. I'm going to evaluate how to implement it and hopefully make it part of the next release

**Comment by bugfest** [comment]
Hi @pingwin! Just released v0.8.0 (helm chart V0.1.10) with namespaced support. Any feedback will be appreciated. Cheers!
