### ISSUE TITLE
[BUG] `OnionService.spec.serviceMonitor` is not declared in schema

### ISSUE THREAD

**Issue by samip5** [bugfest/tor-controller#36]
**Describe the bug**

It seems that `tor.k8s.torproject.org/v1alpha2` CRD doesn't include the serviceMonitor in the schema which should probably be fixed.

The customresourcedefinitions seems to have been updated 5 months ago, despite changes 5 days ago.

**To Reproduce**
Try to deploy OnionService whit v1alpha2 api version.

**Expected behavior**
There would be no issues.

**Additional information**
```
OnionService/tor/ahmia-search dry-run failed, error: .spec.serviceMonitor: field not declared in schema
```

**Comment by bugfest** [comment]
Hi @samip5 are you using namespaced deployment here?

**Comment by samip5** [comment]
> Hi @samip5 are you using namespaced deployment here? 

Yes

**Comment by bugfest** [comment]
Hi @samip5 I cannot reproduce it in my local env. Can you provide more info?
- What's the output of `kubectl explain OnionService.spec`
- And `kubectl get crd/servicemonitors.monitoring.coreos.com`
- Did you install tor-controller using helm or hack/install.yaml?
- Did you upgraded from a previous install? or it is a fresh one?

**Comment by samip5** [comment]
```
$ k explain OnionService.spec
KIND:     OnionService
VERSION:  tor.k8s.torproject.org/v1alpha2

RESOURCE: spec <Object>

DESCRIPTION:
     OnionServiceSpec defines the desired state of OnionService

FIELDS:
   authorizedClients    <[]Object>

   extraConfig  <string>

   masterOnionAddress   <string>

   privateKeySecret     <Object>
     SecretReference represents a Secret Reference

   rules        <[]Object>

   serviceMonitor       <boolean>

   template     <Object>
     Template describes the pods that will be created.

   version      <integer>

$ k get crd/servicemonitors.monitoring.coreos.com
NAME                                    CREATED AT
servicemonitors.monitoring.coreos.com   2023-02-02T02:29:16Z
```

I installed it using Helm, and fresh install. The issue is that if my onionService doesn't include that serviceMonitor field at all, eg https://github.com/samip5/k8s-cluster/blob/main/cluster/apps/tor/services/ahmia-hidden.yaml I get that error.

**Comment by samip5** [comment]
It seems that I was able to deploy the manifest manually so I'm closing this
