### ISSUE TITLE
[REQUEST] Add option to use bridges 

### ISSUE THREAD

**Issue by lexfrei** [bugfest/tor-controller#38]
Please implement support for tor bridges. I'm stuck in a country where I can't use tor directly, so I must use bridges.
I know, it's already in the roadmap, but creating this issue to track the progress.

**Comment by bugfest** [comment]
Hi @lexfrei, thanks for using `tor-controller` and take the time to share your ideas.

Can you detail a bit more your use case? I do have planned to implement custom CRDs to operate bridges, but from your comments I think you mean to use bridges when connecting to Tor network. 

For example, AFAIK to do it in a torrc file, you'd add something like:
```
UseBridges 1
# UpdateBridgesFromAuthority 1
Bridge IP_bridge_1:ORPort1
Bridge IP_bridge_2:ORPort2
Bridge IP_bridge_3:ORPort3
```

Tor Controller currently allows adding extra parameters in the manifest for: 
- Tor daemons: use `spec.config` field
- Onion Services: use `spec.extraConfig` field
- Onion Balanced Services: use `spec.template.extraConfig` field

Does this solve your problem?

**Comment by bugfest** [comment]
Just realized we're not shipping obfs4 binary alongside the tor client binary. Currently you only can achieve this by patching the default container or mounting the binary from a different one. Would that help?

In the end, you'll be enabling bridges like this:
```
apiVersion: tor.k8s.torproject.org/v1alpha2
kind: Tor
metadata:
  name: example-tor-instance-custom-bridges
spec:
  config: |
    # Socks policy:
    SocksPolicy accept 0.0.0.0/0

    UseBridges 1
    # https://bridges.torproject.org/bridges/?transport=obfs4
    Bridge  obfs4 xxx.xxx.xxx.xxxx:4444 C2542268C0F438A725E5225.... cert=7V57ZSaOe59/oSbHNVyQaWyvtPYm.... iat-mode=0
    Bridge obfs4 xxx.xxx.xxx.xxxx:8444 C0CCEBBE5D778.... cert=RTTE2rGpeNSl+QMLvxTov/JQyNJg8SMjez... iat-mode=0
    Bridge obfs4 xxx.xxx.xxx.xxxx:9101 B6461B4E15C0.... cert=hoGthy5+DAGrnL4Iaf67SBUozXf6MecVGE... iat-mode=0

```

**Comment by lexfrei** [comment]
Looks great.
Do you have any plans to add this binary to the image in the next release?

**Comment by bugfest** [comment]
Building new Tor daemon container: https://github.com/bugfest/tor-docker/commit/8ee3b70913d81ffca6bd818dc3d2f2ed62f62e99

**Comment by bugfest** [comment]
Hi @lexfrei, tor-controller release version `0.9.0` (helm chart version `0.1.11`) includes the necessary changes to enable bridges using obfs4 transport. Instructions can be found at https://github.com/bugfest/tor-controller/blob/master/README.md#specifiying-tor-network-bridges.

Let me know how it goes.

Cheers!
