### ISSUE TITLE
[BUG] rollme doesn't work

### ISSUE THREAD

**Issue by lexfrei** [bugfest/tor-controller#51]
**Describe the bug**
Looks like, rollme annotation doesn't work at all

```
a.sviridkin@mbp:~/git/github.com/lexfrei/k8s$ helmfile apply --skip-deps -f ./helmfile.d/network.yaml  | grep rollme
-         rollme: "d06qW"
+         rollme: "nJR94"
Upgrading release=tor-controller, chart=bugfest/tor-controller
Listing releases matching ^tor-controller$

UPDATED RELEASES:
NAME             CHART                    VERSION
tor-controller   bugfest/tor-controller    0.1.11

✓ @ Tue Apr 11 19:54:27 +03 2023
a.sviridkin@mbp:~/git/github.com/lexfrei/k8s$ kubectl get pod tor-controller-7c678d8c76-6ttcw --namespace tor-controller -o yaml | grep rollme
    rollme: J2TUT
✓ @ Tue Apr 11 19:55:46 +03 2023
a.sviridkin@mbp:~/git/github.com/lexfrei/k8s$ kubectl get deployment tor-controller --namespace tor-controller -o yaml | grep rollme
        rollme: J2TUT
✓ @ Tue Apr 11 19:56:25 +03 2023
```

**System (please complete the following information):**
- Chart version: 0.1.11
- K8s version: v1.26.3+k3s1

**Comment by bugfest** [comment]
Thanks for the ticket @lexfrei, gonna investigate it

**Comment by bugfest** [comment]
Hi @lexfrei, I wasn't able to reproduce the issue in my local dev env:

```shell
$ kubectl --namespace -n tor-controller get deployment tor-controller -o yaml | grep rollme
        rollme: AMCnl

$ helm repo update
$ helm upgrade --install --create-namespace --namespace tor-controller tor-controller bugfest/tor-controller

$ kubectl rollout status -n tor deployment/tor-controller
Waiting for deployment "tor-controller" rollout to finish: 1 old replicas are pending termination...
deployment "tor-controller" successfully rolled out

$ kubectl -n tor-controller get deployment
NAME                                             READY   UP-TO-DATE   AVAILABLE   AGE
...
tor-controller                                   1/1     1            1           5d

$ kubectl -n tor-controller get po
NAME                                                              READY   STATUS             RESTARTS        AGE
...
tor-controller-57cb9c9b5f-vlrnd                                   2/2     Running            0               50s

$ kubectl get deployment tor-controller --namespace tor -o yaml | grep rollme
        rollme: OYodB

$ helm version
version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.20.2"}
```

I tested upgrading from `0.1.10->0.1.11` and `0.1.11->0.1.11`. Both ended with a new rollme value and the deployment got rolled out correctly. Can you provide the specific steps to reproduce it?

**Comment by lexfrei** [comment]
Nothing special [here](https://github.com/lexfrei/k8s/blob/33ace59f526066ddca56a3b6eb40dc06bbb1d9f5/helmfile.d/network.yaml#L75-L78). it's the equivalent of the `helm upgrade --install` command with no values.

I can see the new value in the related helm secret in the namespace. But it has no effect on the actual deployment and there is no attempt to recreate it.

Looks like, the `rollout` is used to recreate the deployment to remount the config. I faced this issue in the custom image test.

As you can see in my repo, there is nothing special and in this case, k8s and Helm should work well.

I can make any tests you'll ask for, but for now I won't get extra revisions in helm history on each `helmfile apply`, so I disabled the `rollme` in my case and this is not a problem for me.

**Comment by bugfest** [comment]
I don't have experience with `helmfile`, I wonder if is due to the helm-diff process run under the hood when executing `apply` vs `sync`
