### ISSUE TITLE
[REQUEST] Setup CI to build quay images in this repo

### ISSUE THREAD

**Issue by codekow** [bugfest/tor-controller#54]
**Is your feature request related to a problem? Please describe.**
It's not clear how container images are being built and pushed to quay. Is there automation somewhere else I don't know about that pushes images into quay?

**Describe the solution you'd like**
Can we use github actions in this repo to maintain container images in quay? 

**Describe alternatives you've considered**
Not caring - But I do care 😄

**Comment by drGrove** [comment]
It appears this is already configured

https://github.com/bugfest/tor-controller/actions/runs/4421088778/workflow
https://github.com/bugfest/tor-controller/blob/master/.github/workflows/main-tag.yml

**Comment by bugfest** [comment]
Hi @codekow, images CI workflows are defined at https://github.com/bugfest/tor-controller/tree/master/.github/workflows and are executed as GH Actions aas @drGrove mentions in his comment
