### ISSUE TITLE
[BUG] 0.1.12 chart doesn't run tor-controller-manager

### ISSUE THREAD

**Issue by flrichar** [bugfest/tor-controller#57]
**Describe the bug**
* chart missing config/deployment for tor-controller-manager

**To Reproduce**
* deployment calls `/manager` and can't find the binary ...
```
6m20s       Warning   Failed                           pod/tor-controller-569c85ccd4-vj5td                  Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/manager": stat /manager: no such file or directory: unknown
```
* can edit the deployment to point to `/app/manager` and it works, but then it  errors out because it cannot find `controller_manager_config.yaml`

**Expected behavior**
There are some resources deployed in `hack/install.yaml` that maybe required and not covered in the chart.
Deploying via the `hack/install.yaml` manifest throws errors that one of the resources is too large.

**Additional information**
tested in k3s under amd64 & arm64

**System (please complete the following information):**
 - Platform: amd64, arm64
 - Versions: k3s  (arm64) 1.24.15 & k3s (amd64) 1.25.11
 - Single-Node clusters, amd64 is Rocky Linux VM, arm64 is rpi4 with Ubuntu 20.04

**Additional context**
I had the previous chart (01.11) running on the rpi4 (arm64) for quite a while.

**Comment by bugfest** [comment]
Hi @flrichar, thanks for the heads up! This is due to the size of the `onionbalancedservices` CRD as we import the core v1 pod definition, it carries all the descriptions with it and the resource ends up being too large for the client-side apply. I resolved this in the past by removing the descriptions so that we minimize the size; I'm going to fix the generator/makefile so that this gets done automatically; probably a mock installation might help to spot this in the future.

In the mean time, you can manually install with:
```
kubectl apply -f hack/install.yaml --server-side=true --force-conflicts
```

**Comment by bugfest** [comment]
Now I've spotted the /manager issue, working on it

**Comment by bugfest** [comment]
Hi @flrichar, I've released the patch under a new chart version`0.1.13` https://github.com/bugfest/tor-controller/releases/tag/tor-controller-0.1.13 - please check it and let me know if it works for you too

**Comment by flrichar** [comment]
Thanks for the reply, haven't tried it yet, regarding the descriptions, kinda funny one should not get penalized for good documentation!

**Comment by flrichar** [comment]
Success! It works! Thank you for the quick resonse. 0.1.13 chart running perfectly on both systems.

**Comment by bugfest** [comment]
Thanks for checking @flrichar!
