### ISSUE TITLE
[REQUEST] Move the project to gitlab tor

### ISSUE THREAD

**Issue by MaticPoh** [bugfest/tor-controller#64]
In the future you intend to move the repository to the tor project's gitlab ? so that it can be audited and also maintained by the tor community, the docker images can stay there too. 

Although it is necessary to have an approved account to contribute to the repositories, which would diminish the community that github has, I believe that because the subject is only the tor project, there will be people there who are focused on that and who can help.

**Comment by bugfest** [comment]
Hi @MaticPoh, I consider that option at the begging of the project, but since I was trying to resurrect an abandoned GH project I assumed will be easier for users to find the project here. If the project gets more traction I'll be very happy to move it to GL and leave this one as mirror
