### ISSUE TITLE
[BUG] Don't run as root (tor daemon pod)

### ISSUE THREAD

**Issue by chevdor** [bugfest/tor-controller#69]
**Describe the bug**

Here is a piece of log that says it all:
> Nov 16 22:01:05.000 [warn] You are running Tor as root. You don't need to, and you probably shouldn't.

**To Reproduce**
Use the example.

**Expected behavior**
The container for the tor daemon does not run as root.

**Comment by bugfest** [comment]
Hi @chevdor, what version are you using? I believe we do use non-root UID in `tor-controller-0.1.15-rc.1`. Future releases will also run with non privileged account

**Comment by bugfest** [comment]
Duplicated of #67

**Comment by bugfest** [comment]
@chevdor fix released! https://github.com/bugfest/tor-controller/releases/tag/tor-controller-0.1.15
