### ISSUE TITLE
[BUG] OnionBalancedService, OnionService never get a hostname.

### ISSUE THREAD

**Issue by MattJGH** [bugfest/tor-controller#78]
**Describe the bug**
Forever waiting on hostname to populate. Happens in any configuration - even the example ones

**To Reproduce**
Apply https://github.com/bugfest/tor-controller/blob/master/hack/sample/full-example.yaml (Or any onionservice or onionbalancedservice manifest) to the Cluster

**Expected behavior**
Running kubectl get onion should return a hostname

**What actually happens**
mjgh@hpeserver:~$ kubectl get onion
NAME                            HOSTNAME   AGE
ingress-example-onion-service              5m32s

**System (please complete the following information):**
 - Platform: amd64
 - Version: latest

**Comment by bugfest** [comment]
Hi @MattJGH, did you enable the cluster scoped version? What's the status of the Tor controller? Can you share the logs of the controller?

**Comment by MattJGH** [comment]
Nevermind - Solved by updating and recycling nodes. Sorry to waste time and bandwidth by reporting this haha. Thanks for the help.
